/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

/*!40000 ALTER TABLE `admins` DISABLE KEYS */;
/*!40000 ALTER TABLE `admins` ENABLE KEYS */;

/*!40000 ALTER TABLE `doctor` DISABLE KEYS */;
/*!40000 ALTER TABLE `doctor` ENABLE KEYS */;

/*!40000 ALTER TABLE `ejercicio` DISABLE KEYS */;
/*!40000 ALTER TABLE `ejercicio` ENABLE KEYS */;

/*!40000 ALTER TABLE `extremidad` DISABLE KEYS */;
/*!40000 ALTER TABLE `extremidad` ENABLE KEYS */;

/*!40000 ALTER TABLE `rbac_admin_grupo` DISABLE KEYS */;
/*!40000 ALTER TABLE `rbac_admin_grupo` ENABLE KEYS */;

/*!40000 ALTER TABLE `rbac_grupo` DISABLE KEYS */;
/*!40000 ALTER TABLE `rbac_grupo` ENABLE KEYS */;

/*!40000 ALTER TABLE `rbac_grupo_rol` DISABLE KEYS */;
/*!40000 ALTER TABLE `rbac_grupo_rol` ENABLE KEYS */;

/*!40000 ALTER TABLE `rbac_permiso` DISABLE KEYS */;
/*!40000 ALTER TABLE `rbac_permiso` ENABLE KEYS */;

/*!40000 ALTER TABLE `rbac_rol` DISABLE KEYS */;
/*!40000 ALTER TABLE `rbac_rol` ENABLE KEYS */;

/*!40000 ALTER TABLE `rbac_rol_permiso` DISABLE KEYS */;
/*!40000 ALTER TABLE `rbac_rol_permiso` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
